// stitchd — custom GPU compositor for restitch.
//
// Decodes each camera once (NVDEC), keeps frames in CUDA memory, and builds
// every output from a config with ONE gather kernel per piece — deterministic
// newest-frame-per-tick pairing (no ffmpeg framesync), per-output drop
// scheduling, all GPU-resident. Reproduces restitch's full main pipeline.
//
// Modes:
//   (no args)                 -> capability self-check
//   --config F --out <dir|null|rtsp-base> [--frames N] [--unpaced]
//                             [--hls-dir D]   also write HLS segments under D
//
// The config (generated by the restitch supervisor from config.yaml) is a
// simple line format — see parse_config(). Sources for a piece are
// "composite", an aux input name, or a previously-listed output name (so
// all-field can sample the-field's in-GPU frame directly: no re-decode, no
// re-encode, no second framesync).
//
// See plans/custom-compositor.md.

#include <algorithm>
#include <atomic>
#include <chrono>
#include <condition_variable>
#include <csignal>
#include <cstdio>
#include <cstdlib>
#include <cstring>
#include <filesystem>
#include <fstream>
#include <map>
#include <mutex>
#include <queue>
#include <sstream>
#include <string>
#include <thread>
#include <vector>

extern "C" {
#include <libavcodec/avcodec.h>
#include <libavformat/avformat.h>
#include <libavutil/hwcontext.h>
#include <libavutil/hwcontext_cuda.h>
#include <libavutil/opt.h>
}

#include <cuda_runtime.h>

#if STITCHD_WEBRTC
#include <rtc/rtc.hpp>
#endif

#include "audio.h"
#include "rtsp.h"
#if STITCHD_WEBRTC
#include "webrtc.h"
#endif
#include "cuda_composite.h"

static volatile std::sig_atomic_t g_stop = 0;
// Set once before encoding starts; read-only thereafter.
static rtsp::Server *g_rtsp = nullptr;
#if STITCHD_WEBRTC
static webrtc::Server *g_webrtc = nullptr;
#endif
// Force extradata (SPS/PPS) even when the primary muxer would not ask for it.
// The RTSP server builds its SDP's sprop-parameter-sets from extradata, so
// without this a `--out null` or raw-stream primary silently yields an SDP
// clients cannot decode from ("non-existing PPS 0 referenced").
static bool g_force_global_header = false;

namespace {

std::string av_err(int e) {
  char buf[AV_ERROR_MAX_STRING_SIZE] = {0};
  av_strerror(e, buf, sizeof(buf));
  return buf;
}
#define LOGF(...)                                                              \
  do {                                                                        \
    std::fprintf(stderr, "[stitchd] " __VA_ARGS__);                           \
    std::fprintf(stderr, "\n");                                               \
  } while (0)

enum AVPixelFormat get_hw_format(AVCodecContext *, const enum AVPixelFormat *f) {
  for (const enum AVPixelFormat *p = f; *p != AV_PIX_FMT_NONE; ++p)
    if (*p == AV_PIX_FMT_CUDA)
      return *p;
  return AV_PIX_FMT_NONE;
}

// ---- shared CUDA device (primary context) ---------------------------------
struct Device {
  AVBufferRef *ref = nullptr;
  int create() {
    return av_hwdevice_ctx_create(&ref, AV_HWDEVICE_TYPE_CUDA, "0", nullptr,
                                  AV_CUDA_USE_PRIMARY_CONTEXT);
  }
};

// ---- one threaded decoder; publishes its latest CUDA frame ----------------
class Decoder {
public:
  // `tap` (optional) captures this input's audio; `need_video` false opens an
  // audio-only input (a camera that feeds transcription but no composite).
  // Both share ONE connection to the camera — opening a second one just for
  // audio would double the load on the NVR, which is the thing this whole
  // change exists to avoid.
  int open(const char *url, AVBufferRef *device, audio::Tap *tap = nullptr,
           bool need_video = true) {
    // Remembered so loop() can reopen this input after a drop. Without them a
    // decode thread that lost its connection had nothing to reconnect to and
    // simply exited, freezing that region of every composite it feeds.
    url_ = url;
    device_ = device;
    need_video_ = need_video;
    tap_orig_ = tap;
    return open_input(tap);
  }

private:
  int open_input(audio::Tap *tap) {
    const char *url = url_.c_str();
    AVBufferRef *device = device_;
    const bool need_video = need_video_;
    tap_ = tap;
    AVDictionary *opt = nullptr;
    av_dict_set(&opt, "rtsp_transport", "tcp", 0);
    av_dict_set(&opt, "fflags", "nobuffer", 0);
    // Socket I/O timeout (us): a wedged input errors out of av_read_frame
    // instead of hanging the decode thread forever (last frame is retained).
    av_dict_set(&opt, "timeout", "10000000", 0);
    int err = avformat_open_input(&fmt_, url, nullptr, &opt);
    av_dict_free(&opt);
    if (err < 0) { LOGF("open %s: %s", url, av_err(err).c_str()); return err; }
    if ((err = avformat_find_stream_info(fmt_, nullptr)) < 0) return err;

    if (tap_) {
      int ai = av_find_best_stream(fmt_, AVMEDIA_TYPE_AUDIO, -1, -1, nullptr, 0);
      // A camera with no usable audio contributes silence rather than failing
      // the pipeline — video is the primary job. rebind() on a reconnect, since
      // open() would leak the previous decoder.
      const bool ok = ai >= 0 && (tap_->bound() ? tap_->rebind(fmt_->streams[ai])
                                                : tap_->open(fmt_->streams[ai]));
      if (!ok) tap_ = nullptr;
    }

    // Locate the video stream even when we will not decode it: raw/*
    // passthrough republishes the ORIGINAL packets, so an audio-only input
    // still needs its video stream index and parameters.
    stream_ = av_find_best_stream(fmt_, AVMEDIA_TYPE_VIDEO, -1, -1, nullptr, 0);
    if (stream_ >= 0 && !vpar_) {
      // First open only. The RTSP server has built this stream's SDP from these
      // parameters, so a reconnect must not swap them out underneath live
      // clients — they would be decoding against a description that no longer
      // matches. Same camera, so they should be identical anyway.
      AVStream *vs = fmt_->streams[stream_];
      vpar_ = avcodec_parameters_alloc();
      avcodec_parameters_copy(vpar_, vs->codecpar);
      vtb_ = vs->time_base;
    }

    if (!need_video) return 0;
    if (stream_ < 0) return stream_;
    AVStream *st = fmt_->streams[stream_];
    const AVCodec *dec = avcodec_find_decoder(st->codecpar->codec_id);
    dec_ = avcodec_alloc_context3(dec);
    avcodec_parameters_to_context(dec_, st->codecpar);
    dec_->hw_device_ctx = av_buffer_ref(device);
    dec_->get_format = get_hw_format;
    dec_->pkt_timebase = st->time_base;
    if ((err = avcodec_open2(dec_, dec, nullptr)) < 0) return err;
    return 0;
  }

  // Release everything open_input() acquired, leaving the object reusable.
  // vpar_/vtb_ deliberately survive (see above), as does latest_ — the
  // compositor keeps painting the last good frame while we reconnect, which is
  // better than a black hole in the middle of the composite.
  void close_input() {
    if (dec_) avcodec_free_context(&dec_);
    if (fmt_) avformat_close_input(&fmt_);
    stream_ = -1;
  }

public:
  void start() { thread_ = std::thread([this] { loop(); }); }
  bool latest(AVFrame *dst) {
    std::lock_guard<std::mutex> lk(mu_);
    if (!latest_) return false;
    av_frame_unref(dst);
    return av_frame_ref(dst, latest_) == 0;
  }
  void stop() {
    running_ = false;
    if (thread_.joinable()) thread_.join();
  }
  ~Decoder() {
    stop();
    if (latest_) av_frame_free(&latest_);
    if (dec_) avcodec_free_context(&dec_);
    if (fmt_) avformat_close_input(&fmt_);
  }

private:
  void loop() {
    AVPacket *pkt = av_packet_alloc();
    AVFrame *frame = av_frame_alloc();
    // Outer loop = one connection attempt. Inner loop = reading that
    // connection. Previously there was no outer loop: any read error broke out
    // and the thread ENDED, so a camera reboot or a momentary network blip
    // killed that input until the whole process was restarted, while the
    // compositor happily kept painting its last frame. That is how the
    // Doorbell froze the top half of `entry` for ~15 minutes on 2026-08-10
    // with the camera itself perfectly healthy.
    int backoff_ms = kReconnectMinMs;
    while (running_ && !g_stop) {
      int err = av_read_frame(fmt_, pkt);
      if (err < 0) {
        if (!running_ || g_stop) break;
        LOGF("input '%s' dropped (%s) — reconnecting", log_name().c_str(),
             av_err(err).c_str());
        close_input();
        // Reopen until it takes. Backoff is capped so a camera that is down
        // for hours costs one attempt every kReconnectMaxMs rather than a
        // spin, and so a flapping camera can't hammer the NVR.
        while (running_ && !g_stop) {
          // Sliced rather than one long sleep: stop() joins this thread, and a
          // 30 s nap would hold up shutdown long enough for the supervisor's
          // SIGTERM to be followed by a SIGKILL.
          for (int slept = 0; slept < backoff_ms && running_ && !g_stop;
               slept += 100)
            std::this_thread::sleep_for(std::chrono::milliseconds(100));
          if (!running_ || g_stop) break;
          int rerr = open_input(tap_orig_);
          if (rerr >= 0) {
            LOGF("input '%s' reconnected", log_name().c_str());
            ++reconnects_;
            backoff_ms = kReconnectMinMs;
            break;
          }
          close_input(); // a partial open leaves contexts behind
          backoff_ms = std::min(backoff_ms * 2, kReconnectMaxMs);
        }
        continue;
      }
      backoff_ms = kReconnectMinMs;
      // Audio used to be discarded here; it is the same connection, so taking
      // it costs one decode and no extra network read.
      if (tap_ && pkt->stream_index == tap_->stream_index()) {
        tap_->push_packet(pkt);
        av_packet_unref(pkt);
        continue;
      }
      if (pkt->stream_index != stream_) { av_packet_unref(pkt); continue; }
      // raw/* republish: the camera's ORIGINAL packets, no decode, no
      // re-encode. Lets Home Assistant read per-camera streams from stitchd
      // instead of opening a second connection to the NVR.
      if (g_rtsp && !passthrough_.empty()) g_rtsp->broadcast(passthrough_, pkt);
      if (!dec_) { av_packet_unref(pkt); continue; } // audio-only input
      err = avcodec_send_packet(dec_, pkt);
      av_packet_unref(pkt);
      if (err < 0) continue;
      while ((err = avcodec_receive_frame(dec_, frame)) >= 0) {
        if (frame->format == AV_PIX_FMT_CUDA) publish(frame);
        av_frame_unref(frame);
      }
    }
    av_frame_free(&frame);
    av_packet_free(&pkt);
  }
  void publish(AVFrame *f) {
    AVFrame *copy = av_frame_alloc();
    if (av_frame_ref(copy, f) < 0) { av_frame_free(&copy); return; }
    std::lock_guard<std::mutex> lk(mu_);
    if (latest_) av_frame_free(&latest_);
    latest_ = copy;
    ++count_;
    last_frame_ms_.store(now_ms());
  }

public:
  std::atomic<long long> count_{0};

  // How long since this input produced a frame, in ms; -1 before its first.
  // The compositor keeps painting the last frame of a dead input, so a frozen
  // region is invisible in the output — this is the only thing that makes it
  // detectable. Surfaced in /api/status.
  long long frame_age_ms() const {
    const long long t = last_frame_ms_.load();
    return t ? now_ms() - t : -1;
  }
  long long reconnects() const { return reconnects_.load(); }
  // A name safe to print and to serve from /api/status. The bare URL is not:
  // a UniFi RTSP path is a bearer token in all but name, and the status JSON
  // reaches the dashboard.
  std::string log_name() const {
    if (!passthrough_.empty()) return passthrough_;
    const size_t s = url_.find("://");
    const size_t h = (s == std::string::npos) ? 0 : s + 3;
    const size_t e = url_.find('/', h);
    return e == std::string::npos ? url_ : url_.substr(0, e) + "/...";
  }

private:
  // Reconnect backoff bounds. Min is short so an ordinary blip is invisible;
  // max keeps a camera that is down for hours to one attempt per interval
  // instead of hammering the NVR.
  static constexpr int kReconnectMinMs = 1000;
  static constexpr int kReconnectMaxMs = 30000;

  static long long now_ms() {
    return std::chrono::duration_cast<std::chrono::milliseconds>(
               std::chrono::steady_clock::now().time_since_epoch())
        .count();
  }

  AVFormatContext *fmt_ = nullptr;
  AVCodecContext *dec_ = nullptr;
  int stream_ = -1;
  std::thread thread_;
  std::atomic<bool> running_{true};
  std::mutex mu_;
  AVFrame *latest_ = nullptr;
  audio::Tap *tap_ = nullptr; // not owned
  // Reconnect state: what open() was originally called with.
  std::string url_;
  AVBufferRef *device_ = nullptr; // not owned
  bool need_video_ = true;
  audio::Tap *tap_orig_ = nullptr; // not owned; tap_ is nulled when unusable
  std::atomic<long long> reconnects_{0};
  std::atomic<long long> last_frame_ms_{0};

public:
  // Republish this input's video packets under `name` on the RTSP server.
  void set_passthrough(const std::string &name) { passthrough_ = name; }
  const AVCodecParameters *video_par() const { return vpar_; }
  AVRational video_time_base() const { return vtb_; }

private:
  std::string passthrough_;
  AVCodecParameters *vpar_ = nullptr;
  AVRational vtb_{1, 90000};
};

// ---- one output encoder + muxer -------------------------------------------
struct Output {
  std::string name; // for the RTSP fan-out
  // Encoded packets emitted. The supervisor's watchdog polls this to tell a
  // live output from a wedged one — without it, a stalled encoder looks
  // identical to an idle one and nothing ever restarts the compositor.
  std::atomic<long long> encoded{0};
  AVFormatContext *fmt = nullptr;
  AVCodecContext *enc = nullptr;
  AVStream *stream = nullptr;
  bool header = false;
  // Optional secondary muxer: HLS segments on disk, fed the SAME encoded
  // packets. No second encode — this costs a packet clone and a write, which
  // is why serving HLS ourselves is nearly free once we already own the
  // encoder. (Stage 2 of absorbing mediamtx.)
  AVFormatContext *hls_fmt = nullptr;
  AVStream *hls_stream = nullptr;
  bool hls_header = false;
  bool hls_failed = false;
};

// Open an HLS muxer writing <dir>/<name>/index.m3u8 alongside the primary
// output. fMP4 segments: mpegts cannot carry HEVC in a way every player
// accepts, and `full` is hevc_nvenc.
int open_hls(const std::string &dir, const std::string &name, Output &out) {
  std::string path = dir + "/" + name;
  std::error_code ec;
  std::filesystem::create_directories(path, ec);
  if (ec) { LOGF("hls mkdir %s: %s", path.c_str(), ec.message().c_str()); return -1; }

  std::string playlist = path + "/index.m3u8";
  int err = avformat_alloc_output_context2(&out.hls_fmt, nullptr, "hls",
                                           playlist.c_str());
  if (err < 0 || !out.hls_fmt) { LOGF("hls ctx %s: %s", name.c_str(), av_err(err).c_str()); return -1; }

  out.hls_stream = avformat_new_stream(out.hls_fmt, nullptr);
  if (!out.hls_stream) return -1;
  avcodec_parameters_from_context(out.hls_stream->codecpar, out.enc);
  out.hls_stream->time_base = out.enc->time_base;

  AVDictionary *o = nullptr;
  av_dict_set(&o, "hls_time", "2", 0);
  // A short window keeps latency down and disk bounded; delete_segments stops
  // the directory growing without limit.
  av_dict_set(&o, "hls_list_size", "6", 0);
  av_dict_set(&o, "hls_flags", "delete_segments+independent_segments", 0);
  av_dict_set(&o, "hls_segment_type", "fmp4", 0);
  av_dict_set(&o, "hls_fmp4_init_filename", "init.mp4", 0);
  std::string segpat = path + "/seg%d.m4s";
  av_dict_set(&o, "hls_segment_filename", segpat.c_str(), 0);

  err = avformat_write_header(out.hls_fmt, &o);
  av_dict_free(&o);
  if (err < 0) {
    LOGF("hls header %s: %s", name.c_str(), av_err(err).c_str());
    avformat_free_context(out.hls_fmt);
    out.hls_fmt = nullptr;
    return -1;
  }
  out.hls_header = true;
  LOGF("hls %s -> %s", name.c_str(), playlist.c_str());
  return 0;
}

int open_output(const char *url, const char *codec_name, int w, int h,
                AVBufferRef *frames_ctx, AVRational tb, AVRational fr,
                long maxrate, Output &out) {
  const AVCodec *enc = avcodec_find_encoder_by_name(codec_name);
  if (!enc) { LOGF("no encoder %s", codec_name); return -1; }
  out.enc = avcodec_alloc_context3(enc);
  out.enc->width = w;
  out.enc->height = h;
  out.enc->pix_fmt = AV_PIX_FMT_CUDA;
  out.enc->sw_pix_fmt = AV_PIX_FMT_NV12;
  out.enc->time_base = tb;
  out.enc->framerate = fr;
  out.enc->color_range = AVCOL_RANGE_MPEG;
  out.enc->gop_size = 2 * fr.num / (fr.den ? fr.den : 1); // ~2s
  out.enc->max_b_frames = 0;
  out.enc->hw_frames_ctx = av_buffer_ref(frames_ctx);
  av_opt_set(out.enc->priv_data, "rc", "vbr", 0);
  av_opt_set_int(out.enc->priv_data, "cq", 18, 0);
  av_opt_set(out.enc->priv_data, "preset", "p4", 0);
  av_opt_set(out.enc->priv_data, "tune",
             std::strstr(codec_name, "hevc") ? "hq" : "ll", 0);
  out.enc->bit_rate = 0;
  if (maxrate > 0) {
    out.enc->rc_max_rate = maxrate;
    out.enc->rc_buffer_size = maxrate;
  }

  const bool is_rtsp = std::strncmp(url, "rtsp://", 7) == 0;
  const bool is_null = std::strcmp(url, "null") == 0;
  const char *fmt_name = is_rtsp ? "rtsp" : (is_null ? "null" : nullptr);
  int err;
  if ((err = avformat_alloc_output_context2(&out.fmt, nullptr, fmt_name, url)) <
      0)
    return err;
  if ((out.fmt->oformat->flags & AVFMT_GLOBALHEADER) || g_force_global_header)
    out.enc->flags |= AV_CODEC_FLAG_GLOBAL_HEADER;
  if ((err = avcodec_open2(out.enc, enc, nullptr)) < 0) {
    LOGF("open encoder %s: %s", codec_name, av_err(err).c_str());
    return err;
  }
  out.stream = avformat_new_stream(out.fmt, nullptr);
  avcodec_parameters_from_context(out.stream->codecpar, out.enc);
  out.stream->time_base = out.enc->time_base;
  if (is_rtsp) av_opt_set(out.fmt->priv_data, "rtsp_transport", "tcp", 0);
  if (!(out.fmt->oformat->flags & AVFMT_NOFILE)) {
    if ((err = avio_open(&out.fmt->pb, url, AVIO_FLAG_WRITE)) < 0) return err;
  }
  if ((err = avformat_write_header(out.fmt, nullptr)) < 0) {
    LOGF("write_header(%s): %s", url, av_err(err).c_str());
    return err;
  }
  out.header = true;
  LOGF("output %s: %s %dx%d", url, codec_name, w, h);
  return 0;
}

int drain(Output &out) {
  for (;;) {
    AVPacket *pkt = av_packet_alloc();
    int err = avcodec_receive_packet(out.enc, pkt);
    if (err == AVERROR(EAGAIN) || err == AVERROR_EOF) {
      av_packet_free(&pkt);
      return 0;
    }
    if (err < 0) { av_packet_free(&pkt); return err; }
    ++out.encoded;
    // Clone BEFORE writing: av_interleaved_write_frame consumes the packet.
    AVPacket *hls_pkt =
        (out.hls_fmt && out.hls_header) ? av_packet_clone(pkt) : nullptr;
    // Same encoded packet again for any RTSP clients attached to stitchd
    // directly. Packets stay in the encoder time base; each session's rtp
    // muxer is registered with that same time base.
    AVPacket *rtsp_pkt = g_rtsp ? av_packet_clone(pkt) : nullptr;
#if STITCHD_WEBRTC
    // Must be cloned HERE, before the primary write consumes `pkt`. Cloning it
    // afterwards is a use-after-free (segfault, exit 139).
    AVPacket *wrtc_pkt = g_webrtc ? av_packet_clone(pkt) : nullptr;
#endif

    av_packet_rescale_ts(pkt, out.enc->time_base, out.stream->time_base);
    pkt->stream_index = out.stream->index;
    err = av_interleaved_write_frame(out.fmt, pkt);
    av_packet_free(&pkt);

    if (rtsp_pkt) {
      g_rtsp->broadcast(out.name, rtsp_pkt);
      av_packet_free(&rtsp_pkt);
    }

#if STITCHD_WEBRTC
    if (wrtc_pkt) {
      g_webrtc->broadcast(out.name, wrtc_pkt, out.enc->time_base);
      av_packet_free(&wrtc_pkt);
    }
#endif

    if (hls_pkt) {
      av_packet_rescale_ts(hls_pkt, out.enc->time_base,
                           out.hls_stream->time_base);
      hls_pkt->stream_index = out.hls_stream->index;
      // HLS is a secondary consumer: a failure here must not take down the
      // primary RTSP output, so log once and keep serving.
      int e2 = av_interleaved_write_frame(out.hls_fmt, hls_pkt);
      av_packet_free(&hls_pkt);
      if (e2 < 0 && !out.hls_failed) {
        out.hls_failed = true;
        LOGF("hls write failed (%s) — HLS for this output stops, RTSP continues",
             av_err(e2).c_str());
      }
    }
    if (err < 0) return err;
  }
}

void close_output(Output &out) {
  if (out.hls_fmt && out.hls_header) {
    av_write_trailer(out.hls_fmt);
    if (!(out.hls_fmt->oformat->flags & AVFMT_NOFILE))
      avio_closep(&out.hls_fmt->pb);
  }
  if (out.hls_fmt) { avformat_free_context(out.hls_fmt); out.hls_fmt = nullptr; }
  if (out.fmt && out.header) {
    av_write_trailer(out.fmt);
    if (!(out.fmt->oformat->flags & AVFMT_NOFILE)) avio_closep(&out.fmt->pb);
  }
  if (out.enc) avcodec_free_context(&out.enc);
  if (out.fmt) avformat_free_context(out.fmt);
}

// ---- one output: encode+mux on its own thread behind a bounded queue ------
// The tick submit()s a frame; a full queue (this output not draining) DROPS
// the frame instead of blocking the tick or any sibling. A stuck reader can
// only starve its own stream. Every drop is counted + logged, never silent.
class OutputWorker {
public:
  std::string name;
  int w = 0, h = 0;
  AVBufferRef *frames = nullptr;

  int open(const std::string &url, const std::string &nm, const char *codec,
           int width, int height, long maxrate, AVBufferRef *fr, AVRational tb,
           AVRational frr, int depth, const std::string &hls_dir = "") {
    name = nm;
    w = width;
    h = height;
    frames = av_buffer_ref(fr);
    max_depth_ = depth;
    io_.name = nm;
    if (open_output(url.c_str(), codec, w, h, fr, tb, frr, maxrate, io_) < 0)
      return -1;
    // Best-effort: HLS failing to open must not stop the RTSP output.
    if (!hls_dir.empty()) open_hls(hls_dir, nm, io_);
    th_ = std::thread([this] { loop(); });
    return 0;
  }
  bool submit(AVFrame *f) {
    std::unique_lock<std::mutex> lk(mu_);
    if ((int)q_.size() >= max_depth_) { ++dropped_; return false; }
    q_.push(f);
    cv_.notify_one();
    return true;
  }
  void stop() {
    { std::lock_guard<std::mutex> lk(mu_); running_ = false; }
    cv_.notify_all();
    if (th_.joinable()) th_.join();
    avcodec_send_frame(io_.enc, nullptr);
    drain(io_);
    close_output(io_);
    if (frames) av_buffer_unref(&frames);
  }
  const AVCodecParameters *enc_par() {
    if (!par_) {
      par_ = avcodec_parameters_alloc();
      avcodec_parameters_from_context(par_, io_.enc);
    }
    return par_;
  }
  AVRational enc_time_base() const { return io_.enc->time_base; }
  long long encoded() const { return io_.encoded.load(); }
  void note_pool_drop() { ++dropped_; }
  long long dropped() const { return dropped_; }

private:
  void loop() {
    cudaSetDevice(0);
    const char *sn = std::getenv("STITCHD_SLOW_NAME");
    const int sms = std::getenv("STITCHD_SLOW_MS")
                        ? std::atoi(std::getenv("STITCHD_SLOW_MS")) : 0;
    const bool slow = sn && sms > 0 && name == sn;
    for (;;) {
      AVFrame *f = nullptr;
      {
        std::unique_lock<std::mutex> lk(mu_);
        cv_.wait(lk, [this] { return !q_.empty() || !running_; });
        if (q_.empty() && !running_) break;
        f = q_.front();
        q_.pop();
      }
      if (avcodec_send_frame(io_.enc, f) < 0) LOGF("send_frame(%s)", name.c_str());
      av_frame_free(&f);
      drain(io_);
      if (slow) std::this_thread::sleep_for(std::chrono::milliseconds(sms));
    }
  }
  Output io_{};
  std::queue<AVFrame *> q_;
  std::mutex mu_;
  std::condition_variable cv_;
  std::thread th_;
  bool running_ = true;
  int max_depth_ = 6;
  AVCodecParameters *par_ = nullptr;
  std::atomic<long long> dropped_{0};
};

// =========================================================================
// Config (generated by the restitch supervisor). Line format:
//   fps <n>
//   comp-rot <deg>            ; rotation applied after the vstack
//   comp-dim <w> <h>          ; resolved composite dimensions
//   comp-in <url>             ; one per composite (stacked) camera, in order
//   aux <name> <url>          ; a camera used by extra composites
//   audio-ch <name> <url>     ; a transcription channel, IN ORDER (see below)
//   raw <name> <url>          ; republish this camera verbatim at raw/<name>
//   out <name> <codec> <maxrate>   ; begins an output (maxrate 0 = uncapped)
//   piece <src> <cx> <cy> <cw> <ch> <sw> <sh> <rot>  ; 1+ per out (vstacked)
// `src` = "composite" | an aux name | a previously-declared output name.
// Output dims = pieces[0].sw wide, sum(pieces[i].sh) tall.
struct Piece {
  std::string src;
  int cx, cy, cw, ch, sw, sh, rot;
};
struct OutCfg {
  std::string name, codec;
  long maxrate = 0;
  std::vector<Piece> pieces;
};
struct Config {
  int fps = 30, comp_rot = 0, comp_w = 0, comp_h = 0;
  std::vector<std::string> comp_in;
  std::vector<std::pair<std::string, std::string>> aux; // name,url
  std::vector<OutCfg> outs;
  // Transcription channels, IN ORDER. The consumer interleaves by this order,
  // so it must not be reordered. A URL already opened for video reuses that
  // connection; anything else opens audio-only.
  std::vector<std::pair<std::string, std::string>> audio_ch; // name,url
  // Cameras to republish verbatim as raw/<name>. Lets other consumers (Home
  // Assistant) read per-camera streams from stitchd rather than opening a
  // second connection to the NVR.
  std::vector<std::pair<std::string, std::string>> raw; // name,url
};

bool parse_config(const char *path, Config &c) {
  std::ifstream in(path);
  if (!in) { LOGF("cannot open config %s", path); return false; }
  std::string line;
  while (std::getline(in, line)) {
    std::istringstream ls(line);
    std::string kw;
    if (!(ls >> kw) || kw[0] == '#') continue;
    if (kw == "fps") ls >> c.fps;
    else if (kw == "comp-rot") ls >> c.comp_rot;
    else if (kw == "comp-dim") ls >> c.comp_w >> c.comp_h;
    else if (kw == "comp-in") { std::string u; ls >> u; c.comp_in.push_back(u); }
    else if (kw == "aux") { std::string n, u; ls >> n >> u; c.aux.push_back({n, u}); }
    else if (kw == "raw") {
      // raw <name> <url> — republish this camera's packets at raw/<name>.
      std::string n, u;
      ls >> n >> u;
      c.raw.push_back({n, u});
    }
    else if (kw == "audio-ch") {
      std::string n, u;
      ls >> n >> u;
      c.audio_ch.push_back({n, u});
    }
    else if (kw == "out") {
      OutCfg o;
      ls >> o.name >> o.codec >> o.maxrate;
      c.outs.push_back(o);
    } else if (kw == "piece") {
      if (c.outs.empty()) { LOGF("piece before out"); return false; }
      Piece p;
      ls >> p.src >> p.cx >> p.cy >> p.cw >> p.ch >> p.sw >> p.sh >> p.rot;
      c.outs.back().pieces.push_back(p);
    }
  }
  return true;
}

int selftest() {
  int n = 0;
  bool ok = cudaGetDeviceCount(&n) == cudaSuccess && n > 0;
  ok &= avcodec_find_encoder_by_name("h264_nvenc") != nullptr;
  ok &= avcodec_find_encoder_by_name("hevc_nvenc") != nullptr;
  AVBufferRef *dev = nullptr;
  ok &= av_hwdevice_ctx_create(&dev, AV_HWDEVICE_TYPE_CUDA, nullptr, nullptr,
                               0) >= 0;
  av_buffer_unref(&dev);
#if STITCHD_WEBRTC
  std::printf("webrtc: libdatachannel linked (media=%d)\n", RTC_ENABLE_MEDIA);
#else
  std::printf("webrtc: NOT COMPILED IN\n");
#endif
  std::printf("CUDA devices=%d  %s\n", n, ok ? "PHASE-1A OK" : "FAILED");
  return ok ? 0 : 1;
}

// Y/UV planes + dims for a source this tick.
struct Src {
  const uint8_t *y, *uv;
  int pY, pUV, w, h;
};

#if STITCHD_WEBRTC
int run(const Config &cfg, const char *dest, long long max_frames,
        bool unpaced, const std::string &hls_dir, int rtsp_port,
        const webrtc::Options &webrtc_opt) {
#else
int run(const Config &cfg, const char *dest, long long max_frames,
        bool unpaced, const std::string &hls_dir, int rtsp_port) {
#endif
  av_log_set_level(AV_LOG_ERROR);
  Device dev;
  int err = dev.create();
  if (err < 0) { LOGF("cuda device: %s", av_err(err).c_str()); return 1; }
  cudaSetDevice(0);
  cudaStream_t stream;
  cudaStreamCreate(&stream);

  g_force_global_header = rtsp_port > 0;

  // Which sources are referenced?
  bool need_comp = false;
  std::map<std::string, bool> need_aux;
  for (auto &o : cfg.outs)
    for (auto &p : o.pieces) {
      if (p.src == "composite") need_comp = true;
      for (auto &a : cfg.aux)
        if (p.src == a.first) need_aux[a.first] = true;
    }

  // ---- transcription taps ------------------------------------------------
  // Built BEFORE any decoder so a channel can ride an existing connection.
  // Order is config order and defines the interleave the consumer expects.
  std::vector<std::unique_ptr<audio::Tap>> taps;
  std::vector<audio::Tap *> tap_order;
  std::map<std::string, audio::Tap *> tap_by_url;
  for (auto &ch : cfg.audio_ch) {
    taps.push_back(std::make_unique<audio::Tap>(ch.first));
    tap_order.push_back(taps.back().get());
    tap_by_url[ch.second] = taps.back().get();
  }
  auto tap_for = [&](const std::string &url) -> audio::Tap * {
    auto it = tap_by_url.find(url);
    if (it == tap_by_url.end()) return nullptr;
    audio::Tap *t = it->second;
    tap_by_url.erase(it); // claimed — never attach the same channel twice
    return t;
  };

  // composite decoders
  const int N = (int)cfg.comp_in.size();
  std::vector<Decoder *> decs;
  std::vector<AVFrame *> cur;
  if (need_comp) {
    for (int i = 0; i < N; ++i) {
      auto *d = new Decoder();
      if (d->open(cfg.comp_in[i].c_str(), dev.ref, tap_for(cfg.comp_in[i])) < 0) {
        LOGF("comp decoder %d open failed", i);
        return 1;
      }
      d->start();
      decs.push_back(d);
      cur.push_back(av_frame_alloc());
    }
  }
  // aux decoders (only referenced ones)
  std::map<std::string, Decoder *> auxd;
  std::map<std::string, AVFrame *> auxf;
  for (auto &a : cfg.aux) {
    if (!need_aux[a.first]) continue;
    auto *d = new Decoder();
    if (d->open(a.second.c_str(), dev.ref, tap_for(a.second)) < 0) {
      LOGF("aux %s open failed", a.first.c_str());
      return 1;
    }
    d->start();
    auxd[a.first] = d;
    auxf[a.first] = av_frame_alloc();
  }

  // ---- audio-only inputs + mixer ------------------------------------------
  // Whatever is left in tap_by_url is a camera nobody decodes video for
  // (today: blue and bullet). Open those audio-only — no decoder, no GPU.
  std::vector<Decoder *> audio_only;
  std::map<std::string, Decoder *> audio_only_by_url;
  for (auto &kv : tap_by_url) {
    auto *d = new Decoder();
    if (d->open(kv.first.c_str(), dev.ref, kv.second, /*need_video=*/false) < 0) {
      // Non-fatal: that channel goes silent, the rest of the system is fine.
      LOGF("audio-only input %s open failed — channel silent",
           kv.second->name().c_str());
      delete d;
      continue;
    }
    d->start();
    audio_only.push_back(d);
    audio_only_by_url[kv.first] = d;
  }
  std::unique_ptr<audio::Mixer> mixer;
  if (!tap_order.empty()) {
    // stdout carries the interleaved PCM; all logging goes to stderr, so the
    // two never collide. The supervisor pipes this straight into the existing
    // transcription consumer.
    mixer = std::make_unique<audio::Mixer>(1, tap_order);
    mixer->start();
    LOGF("audio: %zu channels -> stdout (%d Hz s16le interleaved), %zu audio-only inputs",
         tap_order.size(), audio::kSampleRate, audio_only.size());
  }
  LOGF("decoders: %d composite + %zu aux; cold start...", need_comp ? N : 0,
       auxd.size());

  // cold start: wait for a first frame from every decoder
  for (;;) {
    bool all = true;
    for (int i = 0; i < (int)decs.size(); ++i)
      if (!decs[i]->latest(cur[i])) all = false;
    for (auto &kv : auxd)
      if (!kv.second->latest(auxf[kv.first])) all = false;
    if (all || g_stop) break;
    std::this_thread::sleep_for(std::chrono::milliseconds(50));
  }
  if (g_stop) return 1;

  // composite work buffer
  int compW = cfg.comp_w, compH = cfg.comp_h, inW = 0, inH = 0;
  uint8_t *wbY = nullptr, *wbUV = nullptr;
  size_t pY = 0, pUV = 0;
  if (need_comp) {
    inW = cur[0]->width;
    inH = cur[0]->height;
    if (compW == 0) { compW = N * inH; compH = inW; }
    cudaMallocPitch((void **)&wbY, &pY, compW, compH);
    cudaMallocPitch((void **)&wbUV, &pUV, compW, compH / 2);
    LOGF("composite %dx%d from %d x %dx%d", compW, compH, N, inW, inH);
  }

  const bool to_null = std::strcmp(dest, "null") == 0;
  const bool to_rtsp = std::strncmp(dest, "rtsp://", 7) == 0;
  AVRational tb{1, cfg.fps}, fr{cfg.fps, 1};
  const int QDEPTH = 6, POOL = 16;

  // build a worker per output
  std::vector<OutputWorker *> workers;
  for (auto &o : cfg.outs) {
    const int ow = o.pieces[0].sw;
    int oh = 0;
    for (auto &p : o.pieces) oh += p.sh;
    AVBufferRef *frames = av_hwframe_ctx_alloc(dev.ref);
    AVHWFramesContext *fc = (AVHWFramesContext *)frames->data;
    fc->format = AV_PIX_FMT_CUDA;
    fc->sw_format = AV_PIX_FMT_NV12;
    fc->width = ow;
    fc->height = oh;
    fc->initial_pool_size = POOL;
    if ((err = av_hwframe_ctx_init(frames)) < 0) {
      LOGF("hwframe_ctx_init(%s): %s", o.name.c_str(), av_err(err).c_str());
      return 1;
    }
    std::string url = to_null ? "null"
                     : to_rtsp ? std::string(dest) + "/" + o.name
                               : std::string(dest) + "/" + o.name + ".mp4";
    auto *w = new OutputWorker();
    if (w->open(url, o.name, o.codec.c_str(), ow, oh, o.maxrate, frames, tb, fr,
                QDEPTH, hls_dir) < 0)
      return 1;
    av_buffer_unref(&frames);
    workers.push_back(w);
  }

  // Every input, deduplicated by pointer (one Decoder can appear as both a
  // composite input and an aux/audio source). Reported in /api/status so a
  // frozen input is visible: the compositor keeps painting a dead input's last
  // frame, so nothing in the OUTPUT stats can ever reveal one.
  std::vector<Decoder *> all_inputs;
  {
    auto add = [&all_inputs](Decoder *d) {
      if (d && std::find(all_inputs.begin(), all_inputs.end(), d) ==
                   all_inputs.end())
        all_inputs.push_back(d);
    };
    for (auto *d : decs) add(d);
    for (auto &kv : auxd) add(kv.second);
    for (auto *d : audio_only) add(d);
  }

  // Serve the outputs over RTSP ourselves. Registered AFTER the encoders exist
  // so each stream advertises real codec parameters (SPS/PPS, profile, size) —
  // a DESCRIBE built from an unopened encoder yields an SDP clients reject.
#if STITCHD_WEBRTC
  std::unique_ptr<webrtc::Server> webrtc_srv;
  if (webrtc_opt.http_port > 0) {
    webrtc_srv = std::make_unique<webrtc::Server>();
    for (auto *w : workers) webrtc_srv->add_stream(w->name, w->enc_par());
    // Deliberately mediamtx-shaped ({items:[{name,ready,tracks,readers}]}) so
    // the existing dashboard keeps working against a different source rather
    // than needing a rewrite alongside the cutover.
    // Captures the globals, not the locals: rtsp_srv is declared below this
    // point, and both globals are set before any HTTP request can arrive.
    webrtc_srv->set_status_provider([&workers, &all_inputs]() {
      std::ostringstream o;
      o << "{\"items\":[";
      bool first = true;
      for (auto *w : workers) {
        if (!first) o << ",";
        first = false;
        const AVCodecParameters *p = w->enc_par();
        o << "{\"name\":\"" << w->name << "\",\"ready\":true"
          << ",\"codec\":\"" << (p->codec_id == AV_CODEC_ID_HEVC ? "hevc" : "h264")
          << "\",\"width\":" << w->w << ",\"height\":" << w->h
          << ",\"dropped\":" << w->dropped()
          << ",\"frames\":" << w->encoded() << "}";
      }
      o << "],\"sessions\":[";
      bool sfirst = true;
      if (g_rtsp) {
        for (const auto &si : g_rtsp->sessions()) {
          if (!sfirst) o << ",";
          sfirst = false;
          o << "{\"peer\":\"" << si.peer << "\",\"stream\":\"" << si.stream
            << "\",\"via\":\"rtsp/" << si.transport << "\"}";
        }
      }
      if (g_webrtc) {
        for (const auto &vi : g_webrtc->viewer_list()) {
          if (!sfirst) o << ",";
          sfirst = false;
          o << "{\"peer\":\"webrtc\",\"stream\":\"" << vi.stream
            << "\",\"via\":\"webrtc/" << vi.state << "\"}";
        }
      }
      o << "],\"inputs\":[";
      bool ifirst = true;
      for (auto *d : all_inputs) {
        if (!ifirst) o << ",";
        ifirst = false;
        o << "{\"name\":\"" << d->log_name() << "\",\"frames\":" << d->count_
          << ",\"ageMs\":" << d->frame_age_ms()
          << ",\"reconnects\":" << d->reconnects() << "}";
      }
      o << "],\"rtspClients\":" << (g_rtsp ? g_rtsp->client_count() : 0)
        << ",\"webrtcViewers\":" << (g_webrtc ? g_webrtc->viewer_count() : 0)
        << "}";
      return o.str();
    });
    if (webrtc_srv->start(webrtc_opt)) {
      g_webrtc = webrtc_srv.get();
    } else {
      LOGF("webrtc disabled (port %d unavailable)", webrtc_opt.http_port);
      webrtc_srv.reset();
    }
  }
#endif

  // Map every open decoder by URL so a raw/* entry can attach to the
  // connection that already exists rather than opening another one.
  std::map<std::string, Decoder *> by_url;
  for (int i = 0; i < (int)decs.size(); ++i) by_url[cfg.comp_in[i]] = decs[i];
  for (auto &a : cfg.aux) { auto it = auxd.find(a.first); if (it != auxd.end()) by_url[a.second] = it->second; }
  for (auto &kv : audio_only_by_url) by_url[kv.first] = kv.second;

  std::unique_ptr<rtsp::Server> rtsp_srv;
  if (rtsp_port > 0) {
    rtsp_srv = std::make_unique<rtsp::Server>();
    for (auto *w : workers)
      rtsp_srv->add_stream(w->name, w->enc_par(), w->enc_time_base());
    // raw/* passthrough streams, one per camera that has an open connection.
    for (auto &r : cfg.raw) {
      auto it = by_url.find(r.second);
      if (it == by_url.end() || !it->second->video_par()) {
        LOGF("raw/%s: no open input for %s — skipped", r.first.c_str(), r.second.c_str());
        continue;
      }
      const std::string nm = "raw/" + r.first;
      rtsp_srv->add_stream(nm, it->second->video_par(), it->second->video_time_base());
      it->second->set_passthrough(nm);
    }
    if (rtsp_srv->start(rtsp_port)) {
      g_rtsp = rtsp_srv.get();
    } else {
      // Non-fatal: publishing to mediamtx still works, so a taken port must
      // not take the whole compositor down.
      LOGF("rtsp server disabled (port %d unavailable)", rtsp_port);
      rtsp_srv.reset();
    }
  }

  const auto t0 = std::chrono::steady_clock::now();
  long long frames_out = 0;
  while (!g_stop && (max_frames <= 0 || frames_out < max_frames)) {
    if (!unpaced) {
      auto target =
          t0 + std::chrono::microseconds(frames_out * 1000000 / cfg.fps);
      std::this_thread::sleep_until(target);
    }

    // 1) composite (once)
    if (need_comp) {
      CompositeInputs ci{};
      ci.n = N;
      ci.inW = inW;
      ci.inH = inH;
      for (int i = 0; i < N; ++i) {
        decs[i]->latest(cur[i]);
        ci.y[i] = cur[i]->data[0];
        ci.uv[i] = cur[i]->data[1];
        ci.pitchY[i] = cur[i]->linesize[0];
        ci.pitchUV[i] = cur[i]->linesize[1];
      }
      launch_vstack_rotate90cw(&ci, wbY, (int)pY, wbUV, (int)pUV, compW, compH,
                               stream);
    }
    for (auto &kv : auxd) kv.second->latest(auxf[kv.first]);

    // 2) every output: stack its pieces (each a crop+scale+rot gather). Source
    // resolves to composite / aux / a prior output's frame (this tick). Prior
    // outputs are ordered before their consumers in the config, so their
    // frames exist in `built` by the time a consumer reads them (same CUDA
    // stream → the producer kernel has already run).
    std::vector<AVFrame *> ofs(cfg.outs.size(), nullptr);
    std::map<std::string, AVFrame *> built;
    auto resolve = [&](const std::string &s) -> Src {
      if (s == "composite") return {wbY, wbUV, (int)pY, (int)pUV, compW, compH};
      auto ai = auxf.find(s);
      if (ai != auxf.end())
        return {ai->second->data[0], ai->second->data[1],
                ai->second->linesize[0], ai->second->linesize[1],
                ai->second->width, ai->second->height};
      AVFrame *f = built[s];
      return {f->data[0], f->data[1], f->linesize[0], f->linesize[1],
              f->width, f->height};
    };
    for (size_t k = 0; k < cfg.outs.size(); ++k) {
      const OutCfg &o = cfg.outs[k];
      AVFrame *of = av_frame_alloc();
      if (av_hwframe_get_buffer(workers[k]->frames, of, 0) < 0) {
        workers[k]->note_pool_drop();
        av_frame_free(&of);
        continue;
      }
      int yoff = 0;
      for (auto &p : o.pieces) {
        Src s = resolve(p.src);
        uint8_t *dY = of->data[0] + (size_t)yoff * of->linesize[0];
        uint8_t *dUV = of->data[1] + (size_t)(yoff / 2) * of->linesize[1];
        launch_crop_scale_rot180(s.y, s.pY, s.uv, s.pUV, s.w, s.h, p.cx, p.cy,
                                 p.cw, p.ch, dY, of->linesize[0], dUV,
                                 of->linesize[1], p.sw, p.sh, p.rot, stream);
        yoff += p.sh;
      }
      of->pts = frames_out;
      ofs[k] = of;
      built[o.name] = of;
    }

    cudaStreamSynchronize(stream);

    // 3) submit to each worker; queue-full = drop
    for (size_t k = 0; k < cfg.outs.size(); ++k)
      if (ofs[k] && !workers[k]->submit(ofs[k])) av_frame_free(&ofs[k]);

    if (++frames_out % 300 == 0) {
      std::string drops;
      for (auto *w : workers)
        if (w->dropped())
          drops += " " + w->name + "=" + std::to_string(w->dropped());
      LOGF("alive: %lld frames%s", frames_out,
           drops.empty() ? " (0 drops)" : (", drops:" + drops).c_str());
    }
  }

  for (auto *w : workers) { w->stop(); delete w; }
  for (auto *d : decs) d->stop();
  for (auto &kv : auxd) kv.second->stop();
  auto secs =
      std::chrono::duration<double>(std::chrono::steady_clock::now() - t0)
          .count();
  LOGF("done: %lld frames in %.1fs (%.1f fps), %zu outputs", frames_out, secs,
       frames_out / secs, workers.size());
  for (auto *f : cur) av_frame_free(&f);
  for (auto *d : decs) delete d;
  for (auto &kv : auxf) av_frame_free(&kv.second);
  for (auto &kv : auxd) delete kv.second;
  if (wbY) cudaFree(wbY);
  if (wbUV) cudaFree(wbUV);
  cudaStreamDestroy(stream);
  return 0;
}

} // namespace

int main(int argc, char **argv) {
  const char *config = nullptr, *out = nullptr;
  long long max_frames = 0;
  bool unpaced = false;
  std::string hls_dir;
  int rtsp_port = 0;
  int webrtc_http = 0, webrtc_udp = 8189;
  std::vector<std::string> webrtc_hosts, ice_servers;
  for (int i = 1; i < argc; ++i) {
    std::string a = argv[i];
    if (a == "--config" && i + 1 < argc) config = argv[++i];
    else if (a == "--out" && i + 1 < argc) out = argv[++i];
    else if (a == "--frames" && i + 1 < argc) max_frames = std::atoll(argv[++i]);
    else if (a == "--unpaced") unpaced = true;
    // Write HLS (fMP4) for every output under this directory, in addition to
    // the primary RTSP publish. Same encoded packets, no second encode.
    else if (a == "--hls-dir" && i + 1 < argc) hls_dir = argv[++i];
    // Serve the outputs over RTSP directly from stitchd (0 = off).
    else if (a == "--rtsp-port" && i + 1 < argc) rtsp_port = std::atoi(argv[++i]);
    // WebRTC (WHEP). --webrtc-port 0 disables. --webrtc-udp must match the
    // WAN forward. --webrtc-host may repeat (advertised ICE candidates).
    else if (a == "--webrtc-port" && i + 1 < argc) webrtc_http = std::atoi(argv[++i]);
    else if (a == "--webrtc-udp" && i + 1 < argc) webrtc_udp = std::atoi(argv[++i]);
    else if (a == "--webrtc-host" && i + 1 < argc) webrtc_hosts.push_back(argv[++i]);
    else if (a == "--ice-server" && i + 1 < argc) ice_servers.push_back(argv[++i]);
  }
  if (!config || !out) return selftest();

  std::signal(SIGINT, [](int) { g_stop = 1; });
  std::signal(SIGTERM, [](int) { g_stop = 1; });
  Config cfg;
  if (!parse_config(config, cfg)) return 2;
#if STITCHD_WEBRTC
  webrtc::Options wopt;
  wopt.http_port = webrtc_http;
  wopt.udp_mux_port = webrtc_udp;
  wopt.ice_servers = ice_servers;
  wopt.additional_hosts = webrtc_hosts;
  return run(cfg, out, max_frames, unpaced, hls_dir, rtsp_port, wopt);
#else
  if (webrtc_http > 0)
    LOGF("--webrtc-port given but this build has no libdatachannel");
  return run(cfg, out, max_frames, unpaced, hls_dir, rtsp_port);
#endif
}
