// stitchd — custom GPU compositor for restitch.
//
// Decodes each camera once (NVDEC), keeps frames in CUDA memory, and builds
// every output from a config with ONE gather kernel per piece — deterministic
// newest-frame-per-tick pairing (no ffmpeg framesync), per-output drop
// scheduling, all GPU-resident. Reproduces restitch's full main pipeline.
//
// Modes:
//   (no args)                 -> capability self-check
//   --config F --out <dir|null|rtsp-base> [--frames N] [--unpaced]
//
// The config (generated by the restitch supervisor from config.yaml) is a
// simple line format — see parse_config(). Sources for a piece are
// "composite", an aux input name, or a previously-listed output name (so
// all-field can sample the-field's in-GPU frame directly: no re-decode, no
// re-encode, no second framesync).
//
// See plans/custom-compositor.md.

#include <atomic>
#include <chrono>
#include <condition_variable>
#include <csignal>
#include <cstdio>
#include <cstdlib>
#include <cstring>
#include <fstream>
#include <map>
#include <mutex>
#include <queue>
#include <sstream>
#include <string>
#include <thread>
#include <vector>

extern "C" {
#include <libavcodec/avcodec.h>
#include <libavformat/avformat.h>
#include <libavutil/hwcontext.h>
#include <libavutil/hwcontext_cuda.h>
#include <libavutil/opt.h>
}

#include <cuda_runtime.h>

#include "cuda_composite.h"

static volatile std::sig_atomic_t g_stop = 0;

namespace {

std::string av_err(int e) {
  char buf[AV_ERROR_MAX_STRING_SIZE] = {0};
  av_strerror(e, buf, sizeof(buf));
  return buf;
}
#define LOGF(...)                                                              \
  do {                                                                        \
    std::fprintf(stderr, "[stitchd] " __VA_ARGS__);                           \
    std::fprintf(stderr, "\n");                                               \
  } while (0)

enum AVPixelFormat get_hw_format(AVCodecContext *, const enum AVPixelFormat *f) {
  for (const enum AVPixelFormat *p = f; *p != AV_PIX_FMT_NONE; ++p)
    if (*p == AV_PIX_FMT_CUDA)
      return *p;
  return AV_PIX_FMT_NONE;
}

// ---- shared CUDA device (primary context) ---------------------------------
struct Device {
  AVBufferRef *ref = nullptr;
  int create() {
    return av_hwdevice_ctx_create(&ref, AV_HWDEVICE_TYPE_CUDA, "0", nullptr,
                                  AV_CUDA_USE_PRIMARY_CONTEXT);
  }
};

// ---- one threaded decoder; publishes its latest CUDA frame ----------------
class Decoder {
public:
  int open(const char *url, AVBufferRef *device) {
    AVDictionary *opt = nullptr;
    av_dict_set(&opt, "rtsp_transport", "tcp", 0);
    av_dict_set(&opt, "fflags", "nobuffer", 0);
    // Socket I/O timeout (us): a wedged input errors out of av_read_frame
    // instead of hanging the decode thread forever (last frame is retained).
    av_dict_set(&opt, "timeout", "10000000", 0);
    int err = avformat_open_input(&fmt_, url, nullptr, &opt);
    av_dict_free(&opt);
    if (err < 0) { LOGF("open %s: %s", url, av_err(err).c_str()); return err; }
    if ((err = avformat_find_stream_info(fmt_, nullptr)) < 0) return err;
    stream_ = av_find_best_stream(fmt_, AVMEDIA_TYPE_VIDEO, -1, -1, nullptr, 0);
    if (stream_ < 0) return stream_;
    AVStream *st = fmt_->streams[stream_];
    const AVCodec *dec = avcodec_find_decoder(st->codecpar->codec_id);
    dec_ = avcodec_alloc_context3(dec);
    avcodec_parameters_to_context(dec_, st->codecpar);
    dec_->hw_device_ctx = av_buffer_ref(device);
    dec_->get_format = get_hw_format;
    dec_->pkt_timebase = st->time_base;
    if ((err = avcodec_open2(dec_, dec, nullptr)) < 0) return err;
    return 0;
  }
  void start() { thread_ = std::thread([this] { loop(); }); }
  bool latest(AVFrame *dst) {
    std::lock_guard<std::mutex> lk(mu_);
    if (!latest_) return false;
    av_frame_unref(dst);
    return av_frame_ref(dst, latest_) == 0;
  }
  void stop() {
    running_ = false;
    if (thread_.joinable()) thread_.join();
  }
  ~Decoder() {
    stop();
    if (latest_) av_frame_free(&latest_);
    if (dec_) avcodec_free_context(&dec_);
    if (fmt_) avformat_close_input(&fmt_);
  }

private:
  void loop() {
    AVPacket *pkt = av_packet_alloc();
    AVFrame *frame = av_frame_alloc();
    while (running_ && !g_stop) {
      int err = av_read_frame(fmt_, pkt);
      if (err < 0) break;
      if (pkt->stream_index != stream_) { av_packet_unref(pkt); continue; }
      err = avcodec_send_packet(dec_, pkt);
      av_packet_unref(pkt);
      if (err < 0) continue;
      while ((err = avcodec_receive_frame(dec_, frame)) >= 0) {
        if (frame->format == AV_PIX_FMT_CUDA) publish(frame);
        av_frame_unref(frame);
      }
    }
    av_frame_free(&frame);
    av_packet_free(&pkt);
  }
  void publish(AVFrame *f) {
    AVFrame *copy = av_frame_alloc();
    if (av_frame_ref(copy, f) < 0) { av_frame_free(&copy); return; }
    std::lock_guard<std::mutex> lk(mu_);
    if (latest_) av_frame_free(&latest_);
    latest_ = copy;
    ++count_;
  }

public:
  std::atomic<long long> count_{0};

private:
  AVFormatContext *fmt_ = nullptr;
  AVCodecContext *dec_ = nullptr;
  int stream_ = -1;
  std::thread thread_;
  std::atomic<bool> running_{true};
  std::mutex mu_;
  AVFrame *latest_ = nullptr;
};

// ---- one output encoder + muxer -------------------------------------------
struct Output {
  AVFormatContext *fmt = nullptr;
  AVCodecContext *enc = nullptr;
  AVStream *stream = nullptr;
  bool header = false;
};

int open_output(const char *url, const char *codec_name, int w, int h,
                AVBufferRef *frames_ctx, AVRational tb, AVRational fr,
                long maxrate, Output &out) {
  const AVCodec *enc = avcodec_find_encoder_by_name(codec_name);
  if (!enc) { LOGF("no encoder %s", codec_name); return -1; }
  out.enc = avcodec_alloc_context3(enc);
  out.enc->width = w;
  out.enc->height = h;
  out.enc->pix_fmt = AV_PIX_FMT_CUDA;
  out.enc->sw_pix_fmt = AV_PIX_FMT_NV12;
  out.enc->time_base = tb;
  out.enc->framerate = fr;
  out.enc->color_range = AVCOL_RANGE_MPEG;
  out.enc->gop_size = 2 * fr.num / (fr.den ? fr.den : 1); // ~2s
  out.enc->max_b_frames = 0;
  out.enc->hw_frames_ctx = av_buffer_ref(frames_ctx);
  av_opt_set(out.enc->priv_data, "rc", "vbr", 0);
  av_opt_set_int(out.enc->priv_data, "cq", 18, 0);
  av_opt_set(out.enc->priv_data, "preset", "p4", 0);
  av_opt_set(out.enc->priv_data, "tune",
             std::strstr(codec_name, "hevc") ? "hq" : "ll", 0);
  out.enc->bit_rate = 0;
  if (maxrate > 0) {
    out.enc->rc_max_rate = maxrate;
    out.enc->rc_buffer_size = maxrate;
  }

  const bool is_rtsp = std::strncmp(url, "rtsp://", 7) == 0;
  const bool is_null = std::strcmp(url, "null") == 0;
  const char *fmt_name = is_rtsp ? "rtsp" : (is_null ? "null" : nullptr);
  int err;
  if ((err = avformat_alloc_output_context2(&out.fmt, nullptr, fmt_name, url)) <
      0)
    return err;
  if (out.fmt->oformat->flags & AVFMT_GLOBALHEADER)
    out.enc->flags |= AV_CODEC_FLAG_GLOBAL_HEADER;
  if ((err = avcodec_open2(out.enc, enc, nullptr)) < 0) {
    LOGF("open encoder %s: %s", codec_name, av_err(err).c_str());
    return err;
  }
  out.stream = avformat_new_stream(out.fmt, nullptr);
  avcodec_parameters_from_context(out.stream->codecpar, out.enc);
  out.stream->time_base = out.enc->time_base;
  if (is_rtsp) av_opt_set(out.fmt->priv_data, "rtsp_transport", "tcp", 0);
  if (!(out.fmt->oformat->flags & AVFMT_NOFILE)) {
    if ((err = avio_open(&out.fmt->pb, url, AVIO_FLAG_WRITE)) < 0) return err;
  }
  if ((err = avformat_write_header(out.fmt, nullptr)) < 0) {
    LOGF("write_header(%s): %s", url, av_err(err).c_str());
    return err;
  }
  out.header = true;
  LOGF("output %s: %s %dx%d", url, codec_name, w, h);
  return 0;
}

int drain(Output &out) {
  for (;;) {
    AVPacket *pkt = av_packet_alloc();
    int err = avcodec_receive_packet(out.enc, pkt);
    if (err == AVERROR(EAGAIN) || err == AVERROR_EOF) {
      av_packet_free(&pkt);
      return 0;
    }
    if (err < 0) { av_packet_free(&pkt); return err; }
    av_packet_rescale_ts(pkt, out.enc->time_base, out.stream->time_base);
    pkt->stream_index = out.stream->index;
    err = av_interleaved_write_frame(out.fmt, pkt);
    av_packet_free(&pkt);
    if (err < 0) return err;
  }
}

void close_output(Output &out) {
  if (out.fmt && out.header) {
    av_write_trailer(out.fmt);
    if (!(out.fmt->oformat->flags & AVFMT_NOFILE)) avio_closep(&out.fmt->pb);
  }
  if (out.enc) avcodec_free_context(&out.enc);
  if (out.fmt) avformat_free_context(out.fmt);
}

// ---- one output: encode+mux on its own thread behind a bounded queue ------
// The tick submit()s a frame; a full queue (this output not draining) DROPS
// the frame instead of blocking the tick or any sibling. A stuck reader can
// only starve its own stream. Every drop is counted + logged, never silent.
class OutputWorker {
public:
  std::string name;
  int w = 0, h = 0;
  AVBufferRef *frames = nullptr;

  int open(const std::string &url, const std::string &nm, const char *codec,
           int width, int height, long maxrate, AVBufferRef *fr, AVRational tb,
           AVRational frr, int depth) {
    name = nm;
    w = width;
    h = height;
    frames = av_buffer_ref(fr);
    max_depth_ = depth;
    if (open_output(url.c_str(), codec, w, h, fr, tb, frr, maxrate, io_) < 0)
      return -1;
    th_ = std::thread([this] { loop(); });
    return 0;
  }
  bool submit(AVFrame *f) {
    std::unique_lock<std::mutex> lk(mu_);
    if ((int)q_.size() >= max_depth_) { ++dropped_; return false; }
    q_.push(f);
    cv_.notify_one();
    return true;
  }
  void stop() {
    { std::lock_guard<std::mutex> lk(mu_); running_ = false; }
    cv_.notify_all();
    if (th_.joinable()) th_.join();
    avcodec_send_frame(io_.enc, nullptr);
    drain(io_);
    close_output(io_);
    if (frames) av_buffer_unref(&frames);
  }
  void note_pool_drop() { ++dropped_; }
  long long dropped() const { return dropped_; }

private:
  void loop() {
    cudaSetDevice(0);
    const char *sn = std::getenv("STITCHD_SLOW_NAME");
    const int sms = std::getenv("STITCHD_SLOW_MS")
                        ? std::atoi(std::getenv("STITCHD_SLOW_MS")) : 0;
    const bool slow = sn && sms > 0 && name == sn;
    for (;;) {
      AVFrame *f = nullptr;
      {
        std::unique_lock<std::mutex> lk(mu_);
        cv_.wait(lk, [this] { return !q_.empty() || !running_; });
        if (q_.empty() && !running_) break;
        f = q_.front();
        q_.pop();
      }
      if (avcodec_send_frame(io_.enc, f) < 0) LOGF("send_frame(%s)", name.c_str());
      av_frame_free(&f);
      drain(io_);
      if (slow) std::this_thread::sleep_for(std::chrono::milliseconds(sms));
    }
  }
  Output io_{};
  std::queue<AVFrame *> q_;
  std::mutex mu_;
  std::condition_variable cv_;
  std::thread th_;
  bool running_ = true;
  int max_depth_ = 6;
  std::atomic<long long> dropped_{0};
};

// =========================================================================
// Config (generated by the restitch supervisor). Line format:
//   fps <n>
//   comp-rot <deg>            ; rotation applied after the vstack
//   comp-dim <w> <h>          ; resolved composite dimensions
//   comp-in <url>             ; one per composite (stacked) camera, in order
//   aux <name> <url>          ; a camera used by extra composites
//   out <name> <codec> <maxrate>   ; begins an output (maxrate 0 = uncapped)
//   piece <src> <cx> <cy> <cw> <ch> <sw> <sh> <rot>  ; 1+ per out (vstacked)
// `src` = "composite" | an aux name | a previously-declared output name.
// Output dims = pieces[0].sw wide, sum(pieces[i].sh) tall.
struct Piece {
  std::string src;
  int cx, cy, cw, ch, sw, sh, rot;
};
struct OutCfg {
  std::string name, codec;
  long maxrate = 0;
  std::vector<Piece> pieces;
};
struct Config {
  int fps = 30, comp_rot = 0, comp_w = 0, comp_h = 0;
  std::vector<std::string> comp_in;
  std::vector<std::pair<std::string, std::string>> aux; // name,url
  std::vector<OutCfg> outs;
};

bool parse_config(const char *path, Config &c) {
  std::ifstream in(path);
  if (!in) { LOGF("cannot open config %s", path); return false; }
  std::string line;
  while (std::getline(in, line)) {
    std::istringstream ls(line);
    std::string kw;
    if (!(ls >> kw) || kw[0] == '#') continue;
    if (kw == "fps") ls >> c.fps;
    else if (kw == "comp-rot") ls >> c.comp_rot;
    else if (kw == "comp-dim") ls >> c.comp_w >> c.comp_h;
    else if (kw == "comp-in") { std::string u; ls >> u; c.comp_in.push_back(u); }
    else if (kw == "aux") { std::string n, u; ls >> n >> u; c.aux.push_back({n, u}); }
    else if (kw == "out") {
      OutCfg o;
      ls >> o.name >> o.codec >> o.maxrate;
      c.outs.push_back(o);
    } else if (kw == "piece") {
      if (c.outs.empty()) { LOGF("piece before out"); return false; }
      Piece p;
      ls >> p.src >> p.cx >> p.cy >> p.cw >> p.ch >> p.sw >> p.sh >> p.rot;
      c.outs.back().pieces.push_back(p);
    }
  }
  return true;
}

int selftest() {
  int n = 0;
  bool ok = cudaGetDeviceCount(&n) == cudaSuccess && n > 0;
  ok &= avcodec_find_encoder_by_name("h264_nvenc") != nullptr;
  ok &= avcodec_find_encoder_by_name("hevc_nvenc") != nullptr;
  AVBufferRef *dev = nullptr;
  ok &= av_hwdevice_ctx_create(&dev, AV_HWDEVICE_TYPE_CUDA, nullptr, nullptr,
                               0) >= 0;
  av_buffer_unref(&dev);
  std::printf("CUDA devices=%d  %s\n", n, ok ? "PHASE-1A OK" : "FAILED");
  return ok ? 0 : 1;
}

// Y/UV planes + dims for a source this tick.
struct Src {
  const uint8_t *y, *uv;
  int pY, pUV, w, h;
};

int run(const Config &cfg, const char *dest, long long max_frames,
        bool unpaced) {
  av_log_set_level(AV_LOG_ERROR);
  Device dev;
  int err = dev.create();
  if (err < 0) { LOGF("cuda device: %s", av_err(err).c_str()); return 1; }
  cudaSetDevice(0);
  cudaStream_t stream;
  cudaStreamCreate(&stream);

  // Which sources are referenced?
  bool need_comp = false;
  std::map<std::string, bool> need_aux;
  for (auto &o : cfg.outs)
    for (auto &p : o.pieces) {
      if (p.src == "composite") need_comp = true;
      for (auto &a : cfg.aux)
        if (p.src == a.first) need_aux[a.first] = true;
    }

  // composite decoders
  const int N = (int)cfg.comp_in.size();
  std::vector<Decoder *> decs;
  std::vector<AVFrame *> cur;
  if (need_comp) {
    for (int i = 0; i < N; ++i) {
      auto *d = new Decoder();
      if (d->open(cfg.comp_in[i].c_str(), dev.ref) < 0) {
        LOGF("comp decoder %d open failed", i);
        return 1;
      }
      d->start();
      decs.push_back(d);
      cur.push_back(av_frame_alloc());
    }
  }
  // aux decoders (only referenced ones)
  std::map<std::string, Decoder *> auxd;
  std::map<std::string, AVFrame *> auxf;
  for (auto &a : cfg.aux) {
    if (!need_aux[a.first]) continue;
    auto *d = new Decoder();
    if (d->open(a.second.c_str(), dev.ref) < 0) {
      LOGF("aux %s open failed", a.first.c_str());
      return 1;
    }
    d->start();
    auxd[a.first] = d;
    auxf[a.first] = av_frame_alloc();
  }
  LOGF("decoders: %d composite + %zu aux; cold start...", need_comp ? N : 0,
       auxd.size());

  // cold start: wait for a first frame from every decoder
  for (;;) {
    bool all = true;
    for (int i = 0; i < (int)decs.size(); ++i)
      if (!decs[i]->latest(cur[i])) all = false;
    for (auto &kv : auxd)
      if (!kv.second->latest(auxf[kv.first])) all = false;
    if (all || g_stop) break;
    std::this_thread::sleep_for(std::chrono::milliseconds(50));
  }
  if (g_stop) return 1;

  // composite work buffer
  int compW = cfg.comp_w, compH = cfg.comp_h, inW = 0, inH = 0;
  uint8_t *wbY = nullptr, *wbUV = nullptr;
  size_t pY = 0, pUV = 0;
  if (need_comp) {
    inW = cur[0]->width;
    inH = cur[0]->height;
    if (compW == 0) { compW = N * inH; compH = inW; }
    cudaMallocPitch((void **)&wbY, &pY, compW, compH);
    cudaMallocPitch((void **)&wbUV, &pUV, compW, compH / 2);
    LOGF("composite %dx%d from %d x %dx%d", compW, compH, N, inW, inH);
  }

  const bool to_null = std::strcmp(dest, "null") == 0;
  const bool to_rtsp = std::strncmp(dest, "rtsp://", 7) == 0;
  AVRational tb{1, cfg.fps}, fr{cfg.fps, 1};
  const int QDEPTH = 6, POOL = 16;

  // build a worker per output
  std::vector<OutputWorker *> workers;
  for (auto &o : cfg.outs) {
    const int ow = o.pieces[0].sw;
    int oh = 0;
    for (auto &p : o.pieces) oh += p.sh;
    AVBufferRef *frames = av_hwframe_ctx_alloc(dev.ref);
    AVHWFramesContext *fc = (AVHWFramesContext *)frames->data;
    fc->format = AV_PIX_FMT_CUDA;
    fc->sw_format = AV_PIX_FMT_NV12;
    fc->width = ow;
    fc->height = oh;
    fc->initial_pool_size = POOL;
    if ((err = av_hwframe_ctx_init(frames)) < 0) {
      LOGF("hwframe_ctx_init(%s): %s", o.name.c_str(), av_err(err).c_str());
      return 1;
    }
    std::string url = to_null ? "null"
                     : to_rtsp ? std::string(dest) + "/" + o.name
                               : std::string(dest) + "/" + o.name + ".mp4";
    auto *w = new OutputWorker();
    if (w->open(url, o.name, o.codec.c_str(), ow, oh, o.maxrate, frames, tb, fr,
                QDEPTH) < 0)
      return 1;
    av_buffer_unref(&frames);
    workers.push_back(w);
  }

  const auto t0 = std::chrono::steady_clock::now();
  long long frames_out = 0;
  while (!g_stop && (max_frames <= 0 || frames_out < max_frames)) {
    if (!unpaced) {
      auto target =
          t0 + std::chrono::microseconds(frames_out * 1000000 / cfg.fps);
      std::this_thread::sleep_until(target);
    }

    // 1) composite (once)
    if (need_comp) {
      CompositeInputs ci{};
      ci.n = N;
      ci.inW = inW;
      ci.inH = inH;
      for (int i = 0; i < N; ++i) {
        decs[i]->latest(cur[i]);
        ci.y[i] = cur[i]->data[0];
        ci.uv[i] = cur[i]->data[1];
        ci.pitchY[i] = cur[i]->linesize[0];
        ci.pitchUV[i] = cur[i]->linesize[1];
      }
      launch_vstack_rotate90cw(&ci, wbY, (int)pY, wbUV, (int)pUV, compW, compH,
                               stream);
    }
    for (auto &kv : auxd) kv.second->latest(auxf[kv.first]);

    // 2) every output: stack its pieces (each a crop+scale+rot gather). Source
    // resolves to composite / aux / a prior output's frame (this tick). Prior
    // outputs are ordered before their consumers in the config, so their
    // frames exist in `built` by the time a consumer reads them (same CUDA
    // stream → the producer kernel has already run).
    std::vector<AVFrame *> ofs(cfg.outs.size(), nullptr);
    std::map<std::string, AVFrame *> built;
    auto resolve = [&](const std::string &s) -> Src {
      if (s == "composite") return {wbY, wbUV, (int)pY, (int)pUV, compW, compH};
      auto ai = auxf.find(s);
      if (ai != auxf.end())
        return {ai->second->data[0], ai->second->data[1],
                ai->second->linesize[0], ai->second->linesize[1],
                ai->second->width, ai->second->height};
      AVFrame *f = built[s];
      return {f->data[0], f->data[1], f->linesize[0], f->linesize[1],
              f->width, f->height};
    };
    for (size_t k = 0; k < cfg.outs.size(); ++k) {
      const OutCfg &o = cfg.outs[k];
      AVFrame *of = av_frame_alloc();
      if (av_hwframe_get_buffer(workers[k]->frames, of, 0) < 0) {
        workers[k]->note_pool_drop();
        av_frame_free(&of);
        continue;
      }
      int yoff = 0;
      for (auto &p : o.pieces) {
        Src s = resolve(p.src);
        uint8_t *dY = of->data[0] + (size_t)yoff * of->linesize[0];
        uint8_t *dUV = of->data[1] + (size_t)(yoff / 2) * of->linesize[1];
        launch_crop_scale_rot180(s.y, s.pY, s.uv, s.pUV, s.w, s.h, p.cx, p.cy,
                                 p.cw, p.ch, dY, of->linesize[0], dUV,
                                 of->linesize[1], p.sw, p.sh, p.rot, stream);
        yoff += p.sh;
      }
      of->pts = frames_out;
      ofs[k] = of;
      built[o.name] = of;
    }

    cudaStreamSynchronize(stream);

    // 3) submit to each worker; queue-full = drop
    for (size_t k = 0; k < cfg.outs.size(); ++k)
      if (ofs[k] && !workers[k]->submit(ofs[k])) av_frame_free(&ofs[k]);

    if (++frames_out % 300 == 0) {
      std::string drops;
      for (auto *w : workers)
        if (w->dropped())
          drops += " " + w->name + "=" + std::to_string(w->dropped());
      LOGF("alive: %lld frames%s", frames_out,
           drops.empty() ? " (0 drops)" : (", drops:" + drops).c_str());
    }
  }

  for (auto *w : workers) { w->stop(); delete w; }
  for (auto *d : decs) d->stop();
  for (auto &kv : auxd) kv.second->stop();
  auto secs =
      std::chrono::duration<double>(std::chrono::steady_clock::now() - t0)
          .count();
  LOGF("done: %lld frames in %.1fs (%.1f fps), %zu outputs", frames_out, secs,
       frames_out / secs, workers.size());
  for (auto *f : cur) av_frame_free(&f);
  for (auto *d : decs) delete d;
  for (auto &kv : auxf) av_frame_free(&kv.second);
  for (auto &kv : auxd) delete kv.second;
  if (wbY) cudaFree(wbY);
  if (wbUV) cudaFree(wbUV);
  cudaStreamDestroy(stream);
  return 0;
}

} // namespace

int main(int argc, char **argv) {
  const char *config = nullptr, *out = nullptr;
  long long max_frames = 0;
  bool unpaced = false;
  for (int i = 1; i < argc; ++i) {
    std::string a = argv[i];
    if (a == "--config" && i + 1 < argc) config = argv[++i];
    else if (a == "--out" && i + 1 < argc) out = argv[++i];
    else if (a == "--frames" && i + 1 < argc) max_frames = std::atoll(argv[++i]);
    else if (a == "--unpaced") unpaced = true;
  }
  if (!config || !out) return selftest();

  std::signal(SIGINT, [](int) { g_stop = 1; });
  std::signal(SIGTERM, [](int) { g_stop = 1; });
  Config cfg;
  if (!parse_config(config, cfg)) return 2;
  return run(cfg, out, max_frames, unpaced);
}
